#Versão do arquivo docker-compose que será usado.
version: "3.9"

#Defini as redes que serão criadas para a utilização dos nossos serviços
networks:
  algafood-network: #Nome da rede
    driver: bridge #Nome do driver da rede que será usada

#Definindo os nomes dos serviços que serão utilizados
services:
  algafood-mysql: #definindo o nome do container.
    image: mysql:8.0 #Nome da imagem docker que será utilizada
    command: --default-authentication-plugin=mysql_native_password
    environment: #Definindo uma variavel de ambiente
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports: #Porta que será usada pelo container
      - "3307:3306"
    networks: #Nome da rede que o container irá utilizar
      - algafood-network #Estamos utilizando a rede que criamos na chave networks

  algafood-api: #definindo o nome do container.
    image: algafood-api #Nome da imagem docker que será utilizada, nesse caso nós que iremos criar a imagem
    command: ["/wait-for-it.sh", "-t", "30", "algafood-mysql:3307", "--", "java", "-jar", "api.jar"] #Responsvel por executar comandos no momento da inicialização do container
    environment: #Definindo uma variavel de ambiente
      DB_HOST: algafood-mysql
    ports: #Porta que será usada pelo container
      - "8080:8080"
    networks: #Nome da rede que o container irá utilizar
      - algafood-network #Estamos utilizando a rede que criamos na chave networks
    depends_on: #Estamos difinindo que esse container depende do container do banco de dados está no ar para ser iniciado
      - algafood-mysql





